# Generated by Django 4.2.13 on 2024-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeriaCiencias', '0006_alter_articulo_id_alter_artimagen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7, null=True),
        ),
    ]
